import Head from 'next/head'
import Link from 'next/link'

// custom components
import Layout from '../components/Layout'

export default function PageWithGoodName() {
  return (
    <>
      <Head>
        <title>Simple Next.js App - page with good name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1>pageWith<b>Good</b>Name</h1>
        <p>
          You can notice, there's no pageWithBadName located in /pages/pageWithBadName.js.
          I used next.js rewrites to deal with it and also to keep URL same as is in the link.
          <br/>
          <br/>
          <Link href="/">
            <a>Link back</a>
          </Link>
        </p>
      </Layout>
    </>
  )
}
